spring.application.name=foodFrenzy
spring.datasource.url=jdbc:mysql://localhost:3306/foodfrenzy
spring.datasource.username=root
spring.datasource.password=Krithi@2109

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9092